### ISSUE TITLE
SIGILL in OPENSSL_ia32_cpuid

### ISSUE THREAD

**Issue by aep** [deislabs/mystikos#1323]
when running any app with myst-gdb i'm getting a SIGILL inside the OE libcrypto

```
Program received signal SIGILL, Illegal instruction.
OPENSSL_ia32_cpuid () at build/crypto/x86_64cpuid.s:46
46	build/crypto/x86_64cpuid.s: No such file or directory.
(gdb) bt
#0  OPENSSL_ia32_cpuid () at build/crypto/x86_64cpuid.s:46
#1  0x000000010019a26c in OPENSSL_cpuid_setup () at /source/mystikos/third_party/openenclave/openenclave/3rdparty/openssl/openssl/crypto/cryptlib.c:149
#2  0x000000010020cfed in ossl_init_base () at /source/mystikos/third_party/openenclave/openenclave/3rdparty/openssl/openssl/crypto/init.c:103
#3  0x000000010020ccd9 in ossl_init_base_ossl_ () at /source/mystikos/third_party/openenclave/openenclave/3rdparty/openssl/openssl/crypto/init.c:89
#4  0x000000010025cb44 in CRYPTO_THREAD_run_once (once=0x100568144 <base>, init=0x10020ccd0 <ossl_init_base_ossl_>)
    at /source/mystikos/third_party/openenclave/openenclave/3rdparty/openssl/openssl/crypto/threads_none.c:70
#5  0x000000010020ade5 in OPENSSL_init_crypto (opts=512, settings=0x0) at /source/mystikos/third_party/openenclave/openenclave/3rdparty/openssl/openssl/crypto/init.c:639
#6  0x000000010015ba66 in _initialize_rdrand_engine () at /source/mystikos/third_party/openenclave/openenclave/enclave/crypto/openssl/init.c:31
#7  0x000000010015b84d in _initialize () at /source/mystikos/third_party/openenclave/openenclave/enclave/crypto/openssl/init.c:87
#8  0x0000000100139d76 in oe_once (once=0x100567f60 <_openssl_initialize_once>, func=0x10015b7c0 <_initialize>)
    at /source/mystikos/third_party/openenclave/openenclave/enclave/core/once.c:62
#9  0x000000010015b7b7 in oe_crypto_initialize () at /source/mystikos/third_party/openenclave/openenclave/enclave/crypto/openssl/init.c:93
#10 0x000000010010e7f0 in _handle_init_enclave (arg_in=1099530695696) at /source/mystikos/third_party/openenclave/openenclave/enclave/core/sgx/calls.c:194
#11 0x000000010010db1b in _handle_ecall (td=0x1873bd000, func=1, arg_in=1099530695696, output_arg1=0x1873b6fd8, output_arg2=0x1873b6fd0)
    at /source/mystikos/third_party/openenclave/openenclave/enclave/core/sgx/calls.c:569
#12 0x000000010010cfe3 in __oe_handle_main (arg1=281479271677952, arg2=1099530695696, cssa=0, tcs=0x1873b8000, output_arg1=0x1873b6fd8, output_arg2=0x1873b6fd0)
    at /source/mystikos/third_party/openenclave/openenclave/enclave/core/sgx/calls.c:1207
#13 0x000000010010f3c6 in oe_enter () at /source/mystikos/third_party/openenclave/openenclave/enclave/core/sgx/enter.S:322
#14 0x00000100000bf9eb in __morestack (tcs=<optimized out>, aep=1099512411988, arg1=4300648760, arg2=4296646348, arg3=0x7fffd5c247b0, arg4=0x7fffd5c247a8,
    enclave=0x1000122f410) at /source/mystikos/third_party/openenclave/openenclave/host/sgx/enter.c:221
#15 0x00000100000ab2c8 in _do_eenter (enclave=0x1000122f410, tcs=0x1873b8000, aep=1099512411988, code_in=OE_CODE_ECALL, func_in=1, arg_in=1099530695696,
    code_out=0x7fffd5c247a4, func_out=0x7fffd5c247a2, result_out=0x7fffd5c247a0, arg_out=0x7fffd5c24798)
    at /source/mystikos/third_party/openenclave/openenclave/host/sgx/calls.c:194
#16 oe_ecall (enclave=0x1000122f410, func=1, arg=1099530695696, arg_out_ptr=0x7fffd5c248f0) at /source/mystikos/third_party/openenclave/openenclave/host/sgx/calls.c:614
#17 0x000001000004a522 in _initialize_enclave (enclave=0x1000122f410) at /source/mystikos/third_party/openenclave/openenclave/host/sgx/create.c:554
#18 0x0000010000049e6d in oe_create_enclave (enclave_path=0x7fffd5c27e40 "/tmp/mystfjsjVV/lib/openenclave/mystenc.so", enclave_type=OE_ENCLAVE_TYPE_SGX, flags=16,
    settings=0x7fffd5c24e80, setting_count=1, ocall_table=0x1000011c060 <_myst_ocall_function_table>, ocall_count=103,
    ecall_name_table=0x10000118560 <_myst_ecall_info_table>, ecall_count=7, enclave_out=0x1000011d880 <_enclave>)
    at /source/mystikos/third_party/openenclave/openenclave/host/sgx/create.c:1336
#19 0x000001000001faf9 in oe_create_myst_enclave (path=0x7fffd5c27e40 "/tmp/mystfjsjVV/lib/openenclave/mystenc.so", type=OE_ENCLAVE_TYPE_SGX, flags=16,
    settings=0x7fffd5c24e80, setting_count=1, enclave=0x1000011d880 <_enclave>) at /source/mystikos/build/obj/tools/myst/host/myst_u.c:8562
#20 0x0000010000020261 in exec_launch_enclave (enc_path=0x7fffd5c27e40 "/tmp/mystfjsjVV/lib/openenclave/mystenc.so", type=OE_ENCLAVE_TYPE_SGX, flags=16, argv=0x100011dbf10,
    envp=0x7fffd5c28fd8, mount_mappings=0x7fffd5c25050, options=0x7fffd5c251c0) at exec.c:251
#21 0x00000100000237b7 in _exec_package (argc=1, argv=0x7fffd5c28fc8, envp=0x7fffd5c28fd8, executable=0x7fffd5c28fc8 "\276\250\302\325\377\177") at package.c:940
#22 0x000001000002b702 in _main (argc=1, argv=0x7fffd5c28fc8, envp=0x7fffd5c28fd8) at host.c:420
#23 0x000001000002ba18 in main (argc=1, argv=0x7fffd5c28fc8, envp=0x7fffd5c28fd8) at host.c:498
```

**Comment by aep** [comment]
apparantly SYSCALL is also a SIGILL. This is not an issue when running without gdb
