### ISSUE TITLE
Support SYS_eventfd2

### ISSUE THREAD

**Issue by praenubilus** [deislabs/mystikos#142]
Trying to make a C++ Web Server (https://github.com/microsoft/cpprestsdk) work inside mystikos. When the service starts, syscall failed on SYS_eventfd2, which is a not supported syscall. Following is the stack trace:

```
#0  0x00007fff803b8e3c in myst_crash () at /home/xuejun/myst/include/myst/crash.h:11
#1  0x00007fff803b8f78 in __myst_panic (file=0x7fff803fa2c7 "syscall.c", line=4347, 
    func=0x7fff803fc790 <__FUNCTION__.7711> "myst_syscall", 
    format=0x7fff803fafa7 "unhandled syscall: %s()") at panic.c:34
#2  0x00007fff803c3307 in myst_syscall (n=290, params=0x7fffa2755c50) at syscall.c:4347
#3  0x00007fffa2f73176 in myst_syscall (n=290, params=0x7fffa2755c50) at enter.c:37
#4  0x00007fffa2f8a3c2 in __syscall2 (n=290, a1=0, a2=526336) at ./arch/x86_64/syscall_arch.h:24
#5  0x00007fffa2f8a3e8 in eventfd (count=0, flags=526336) at src/linux/eventfd.c:8
#6  0x00007fffa2e60f1d in boost::asio::detail::eventfd_select_interrupter::open_descriptors (
    this=0x7fff836963a8) at /usr/include/boost/asio/detail/impl/eventfd_select_interrupter.ipp:59
#7  0x00007fffa2e60eee in boost::asio::detail::eventfd_select_interrupter::eventfd_select_interrupter
    (this=0x7fff836963a8) at /usr/include/boost/asio/detail/impl/eventfd_select_interrupter.ipp:44
#8  0x00007fffa2e614ab in boost::asio::detail::epoll_reactor::epoll_reactor (this=0x7fff83696340, 
    ctx=...) at /usr/include/boost/asio/detail/impl/epoll_reactor.ipp:47
#9  0x00007fffa2e72487 in boost::asio::detail::service_registry::create<boost::asio::detail::epoll_reactor, boost::asio::execution_context> (
    owner=0x7fffa2f5d2c8 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool+8>) at /usr/include/boost/asio/detail/impl/service_registry.hpp:87
#10 0x00007fffa2e60cbd in boost::asio::detail::service_registry::do_use_service (this=0x7fffa29c3a80, 
    key=..., 
    factory=0x7fffa2e7245c <boost::asio::detail::service_registry::create<boost::asio::detail::epoll_reactor, boost::asio::execution_context>(void*)>, 
    owner=0x7fffa2f5d2c8 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool+8>) at /usr/include/boost/asio/detail/impl/service_registry.ipp:132
#11 0x00007fffa2e6e008 in boost::asio::detail::service_registry::use_service<boost::asio::detail::epoll_reactor> (this=0x7fffa29c3a80) at /usr/include/boost/asio/detail/impl/service_registry.hpp:30
#12 0x00007fffa2e68d36 in boost::asio::use_service<boost::asio::detail::epoll_reactor> (e=...)
    at /usr/include/boost/asio/impl/execution_context.hpp:35
#13 0x00007fffa2e66692 in boost::asio::detail::reactive_socket_service_base::reactive_socket_service_base (this=0x7fff83696328, context=...)
    at /usr/include/boost/asio/detail/impl/reactive_socket_service_base.ipp:33
#14 0x00007fffa2e7baf9 in boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp>::reactive_socket_service (this=0x7fff83696300, context=...)
    at /usr/include/boost/asio/detail/reactive_socket_service.hpp:80
#15 0x00007fffa2e79b6d in boost::asio::detail::service_registry::create<boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp>, boost::asio::io_context> (
    owner=0x7fffa2f5d2c8 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool+8>) at /usr/include/boost/asio/detail/impl/service_registry.hpp:87
#16 0x00007fffa2e60cbd in boost::asio::detail::service_registry::do_use_service (this=0x7fffa29c3a80, 
--Type <RET> for more, q to quit, c to continue without paging--
    key=..., 
    factory=0x7fffa2e79b42 <boost::asio::detail::service_registry::create<boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp>, boost::asio::io_context>(void*)>, 
    owner=0x7fffa2f5d2c8 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool+8>) at /usr/include/boost/asio/detail/impl/service_registry.ipp:132
#17 0x00007fffa2e77388 in boost::asio::detail::service_registry::use_service<boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp> > (this=0x7fffa29c3a80, owner=...)
    at /usr/include/boost/asio/detail/impl/service_registry.hpp:39
#18 0x00007fffa2e73f0b in boost::asio::use_service<boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp> > (ioc=...) at /usr/include/boost/asio/impl/io_context.hpp:42
#19 0x00007fffa2e6fbde in boost::asio::detail::io_object_impl<boost::asio::detail::reactive_socket_service<boost::asio::ip::tcp>, boost::asio::executor>::io_object_impl<boost::asio::io_context> (
    this=0x7fff836962c0, context=...) at /usr/include/boost/asio/detail/io_object_impl.hpp:86
#20 0x00007fffa2e6ada1 in boost::asio::basic_socket_acceptor<boost::asio::ip::tcp, boost::asio::executor>::basic_socket_acceptor<boost::asio::io_context> (this=0x7fff836962c0, context=...)
    at /usr/include/boost/asio/basic_socket_acceptor.hpp:142
#21 0x00007fffa2e1859f in (anonymous namespace)::hostport_listener::start (this=0x7fff83695ea0)
    at ../Release/src/http/listener/http_server_asio.cpp:529
#22 0x00007fffa2e1dcf4 in (anonymous namespace)::http_linux_server::register_listener (
    this=0x7fff83695da0, listener=0x7fffa2d17580)
    at ../Release/src/http/listener/http_server_asio.cpp:1360
#23 0x00007fffa2dead9b in web::http::experimental::details::http_server_api::<lambda()>::operator()(void) const (__closure=0x7fffa2d179a0) at ../Release/src/http/listener/http_server_api.cpp:96
#24 0x00007fffa2dec8f1 in std::_Function_handler<void(), web::http::experimental::details::http_server_api::register_listener(web::http::experimental::listener::details::http_listener_impl*)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/9.3.0/bits/std_function.h:300
#25 0x00007fffa2d4285e in std::function<void ()>::operator()() const (this=0x7fffa2d179a0)
    at /usr/include/c++/9.3.0/bits/std_function.h:688
#26 0x00007fffa2decce5 in pplx::details::_MakeVoidToUnitFunc(std::function<void ()> const&)::{lambda()#1}::operator()() const (__closure=0x7fffa2d179a0) at ../Release/include/pplx/pplxtasks.h:2630
#27 0x00007fffa2ded1c1 in std::_Function_handler<unsigned char (), pplx::details::_MakeVoidToUnitFunc(std::function<void ()> const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/9.3.0/bits/std_function.h:285
#28 0x00007fffa2ded9b8 in std::function<unsigned char ()>::operator()() const (this=0x7fffa27564c0)
    at /usr/include/c++/9.3.0/bits/std_function.h:688
#29 0x00007fffa2dec6f7 in pplx::task<unsigned char>::_InitialTaskHandle<void, web::http::experimental::details::http_server_api::register_listener(web::http::experimental::listener::details::http_listener_impl*)::<lambda()>, pplx::details::_TypeSelectorNoAsync>::_LogWorkItemAndInvokeUserLambda<std::function<unsigned char()> >(std::function<unsigned char()> &&) const (this=0x7fffa2d178c0, _func=...)
--Type <RET> for more, q to quit, c to continue without paging--
    at ../Release/include/pplx/pplxtasks.h:3803
#30 0x00007fffa2dec4b4 in pplx::task<unsigned char>::_InitialTaskHandle<void, web::http::experimental::details::http_server_api::register_listener(web::http::experimental::listener::details::http_listener_impl*)::<lambda()>, pplx::details::_TypeSelectorNoAsync>::_Init(pplx::details::_TypeSelectorNoAsync) const (this=0x7fffa2d178c0) at ../Release/include/pplx/pplxtasks.h:3817
#31 0x00007fffa2dec357 in pplx::task<unsigned char>::_InitialTaskHandle<void, web::http::experimental::details::http_server_api::register_listener(web::http::experimental::listener::details::http_listener_impl*)::<lambda()>, pplx::details::_TypeSelectorNoAsync>::_Perform(void) const (this=0x7fffa2d178c0)
    at ../Release/include/pplx/pplxtasks.h:3806
#32 0x00007fffa2dec159 in pplx::details::_PPLTaskHandle<unsigned char, pplx::task<unsigned char>::_InitialTaskHandle<void, web::http::experimental::details::http_server_api::register_listener(web::http::experimental::listener::details::http_listener_impl*)::<lambda()>, pplx::details::_TypeSelectorNoAsync>, pplx::details::_TaskProcHandle>::invoke(void) const (this=0x7fffa2d178c0)
    at ../Release/include/pplx/pplxtasks.h:1645
#33 0x00007fffa2d3d5ec in pplx::details::_TaskProcHandle::_RunChoreBridge (_Parameter=0x7fffa2d178c0)
    at /app/include/pplx/pplx.h:113
#34 0x00007fffa2e0eba3 in boost::_bi::list1<boost::_bi::value<void*> >::operator()<void (*)(void*), boost::_bi::list0> (this=0x7fffa27567a8, 
    f=@0x7fffa27567a0: 0x7fffa2d3d59e <pplx::details::_TaskProcHandle::_RunChoreBridge(void*)>, a=...)
    at /usr/include/boost/bind/bind.hpp:259
#35 0x00007fffa2e0eb46 in boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >::operator() (this=0x7fffa27567a0) at /usr/include/boost/bind/bind.hpp:1294
#36 0x00007fffa2e0eafe in boost::asio::asio_handler_invoke<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (function=...)
    at /usr/include/boost/asio/handler_invoke_hook.hpp:69
#37 0x00007fffa2e0ea93 in boost_asio_handler_invoke_helpers::invoke<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >, boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (function=..., context=...)
    at /usr/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#38 0x00007fffa2e0ea11 in boost::asio::detail::handler_work<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > >, boost::asio::system_executor, boost::asio::system_executor>::complete<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > > (this=0x7fffa2756796, function=..., handler=...)
    at /usr/include/boost/asio/detail/handler_work.hpp:100
#39 0x00007fffa2e0e88c in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > >::do_complete (owner=0x7fffa2942d80, 
    base=0x7fffa2d17900) at /usr/include/boost/asio/detail/completion_handler.hpp:70
#40 0x00007fffa2e110be in boost::asio::detail::scheduler_operation::complete (this=0x7fffa2d17900, 
    owner=0x7fffa2942d80, ec=..., bytes_transferred=0)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/boost/asio/detail/scheduler_operation.hpp:40
#41 0x00007fffa2e12d04 in boost::asio::detail::scheduler::do_run_one (this=0x7fffa2942d80, lock=..., 
    this_thread=..., ec=...) at /usr/include/boost/asio/detail/impl/scheduler.ipp:447
#42 0x00007fffa2e12a84 in boost::asio::detail::scheduler::run (this=0x7fffa2942d80, ec=...)
    at /usr/include/boost/asio/detail/impl/scheduler.ipp:200
#43 0x00007fffa2e12f80 in boost::asio::io_context::run (
    this=0x7fffa2f5d2c8 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool+8>) at /usr/include/boost/asio/impl/io_context.ipp:63
#44 0x00007fffa2e10422 in (anonymous namespace)::threadpool_impl::thread_start (
    arg=0x7fffa2f5d2c0 <(anonymous namespace)::initialize_shared_threadpool(unsigned long)::uninit_threadpool>) at ../Release/src/pplx/threadpool.cpp:79
#45 0x00007fffa2e10333 in (anonymous namespace)::threadpool_impl::<lambda()>::operator()(void) const (
    __closure=0x7fffa29c3ae8) at ../Release/src/pplx/threadpool.cpp:64
#46 0x00007fffa2e10cb4 in boost::asio::detail::posix_thread::func<(anonymous namespace)::threadpool_impl::add_thread()::<lambda()> >::run(void) (this=0x7fffa29c3ae0)
    at /usr/include/boost/asio/detail/posix_thread.hpp:86
#47 0x00007fffa2e11c23 in boost::asio::detail::boost_asio_detail_posix_thread_function (
    arg=0x7fffa29c3ae0) at /usr/include/boost/asio/detail/impl/posix_thread.ipp:74
#48 0x00007fffa2fec68c in start (p=0x7fffa2756ab0) at src/thread/pthread_create.c:192
#49 0x00007fff803da542 in _call_thread_fn () at thread.c:384
#50 0x00007fffa2e11be8 in boost::asio::detail::posix_thread::start_thread (
    this=0x7fff803da542 <_call_thread_fn+59>, arg=0x7fffa2756aa0)
    at /usr/include/boost/asio/detail/impl/posix_thread.ipp:68
#51 0x00007fffa29c3ae0 in ?? ()
#52 0x0000000000000000 in ?? ()

```

**Comment by bodzhang** [comment]
NodeJs also triggered eventfd2 syscall.

**Comment by praenubilus** [comment]
Boost.asio will also trigger eventfd2 syscall

**Comment by praenubilus** [comment]
Issue can be closed.
