### ISSUE TITLE
Support SYS_fork

### ISSUE THREAD

**Issue by praenubilus** [deislabs/mystikos#172]
3rd party application Pytorch will crash for unhandled syscall `SYS_fork`. Below is a sample error information from `myst exec`. More details can be found in application sample PR https://github.com/deislabs/mystikos/pull/173

```bash
*** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
0x7f2a003bb0f1: __myst_panic()
0x7f2a003c5bba: myst_syscall()
0x7f2a415f72a6: unknown
0x7f2a41647e6b: unknown
0x7f2a41647eb2: unknown
0x7f2a40efb6f7: unknown
0x7f2a415b2be0: unknown
```

**Comment by jxyang** [comment]
Can you produce a call stack for SYS_fork?

**Comment by praenubilus** [comment]
```gdb
oegdb: Loaded enclave image /tmp/mystNnHXsJ
oegdb: Loaded enclave image /tmp/mystOZGfYQ
oegdb: Loaded enclave image /tmp/mystASyCgC
oegdb: Loaded enclave image /tmp/mysth5qd9u
oegdb: Loaded enclave image /tmp/myst82A06n
oegdb: Loaded enclave image /tmp/mystlxIx9g
*** kernel panic: syscall.c(4464): myst_syscall(): unhandled syscall: SYS_fork()
0x7ffe003bb0f1: __myst_panic()
0x7ffe003c5bba: myst_syscall()
0x7ffe415f72a6: unknown
0x7ffe41647e6b: unknown
0x7ffe41647eb2: unknown
0x7ffe40ec16f7: unknown
0x7ffe415b2be0: unknown

Thread 1 "myst" received signal SIGSEGV, Segmentation fault.
0x00007ffe003bb06c in myst_crash () at /home/wyh/workspaces/app/mystikos/include/myst/crash.h:11
11          *((volatile unsigned char*)0) = 0;
(gdb) bt
#0  0x00007ffe003bb06c in myst_crash ()
    at /home/wyh/workspaces/app/mystikos/include/myst/crash.h:11
#1  0x00007ffe003bb1a8 in __myst_panic (file=0x7ffe003fef67 "syscall.c", line=4464, 
    func=0x7ffe004014e0 <__FUNCTION__.7793> "myst_syscall", 
    format=0x7ffe003ffcb8 "unhandled syscall: %s()") at panic.c:34
#2  0x00007ffe003c5bba in myst_syscall (n=57, params=0x7ffe422ae6c0) at syscall.c:4464
#3  0x00007ffe415f72a6 in myst_syscall (n=57, params=0x7ffe422ae6c0) at enter.c:37
#4  0x00007ffe41647e6b in __syscall0 (n=57) at ./arch/x86_64/syscall_arch.h:9
#5  0x00007ffe41647eb2 in fork () at src/process/fork.c:21
#6  0x00007ffe40ec16f7 in ?? ()
#7  0x00007ffe41416662 in _PyMethodDef_RawFastCallKeywords ()
#8  0x00007ffe4141672f in _PyCFunction_FastCallKeywords ()
#9  0x00007ffe4142916f in ?? ()
#10 0x00007ffe41447351 in _PyEval_EvalFrameDefault ()
#11 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#12 0x00007ffe41403f94 in _PyFunction_FastCallKeywords ()
#13 0x00007ffe414292fd in ?? ()
#14 0x00007ffe4144736c in _PyEval_EvalFrameDefault ()
#15 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#16 0x00007ffe413f0ef6 in _PyFunction_FastCallDict ()
#17 0x00007ffe413f5945 in _PyObject_Call_Prepend ()
#18 0x00007ffe414286b6 in ?? ()
#19 0x00007ffe41429404 in ?? ()
#20 0x00007ffe4141686f in _PyObject_FastCallKeywords ()
#21 0x00007ffe41429304 in ?? ()
#22 0x00007ffe4144747f in _PyEval_EvalFrameDefault ()
#23 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#24 0x00007ffe41403f94 in _PyFunction_FastCallKeywords ()
#25 0x00007ffe414292fd in ?? ()
#26 0x00007ffe41447351 in _PyEval_EvalFrameDefault ()
#27 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#28 0x00007ffe41403f94 in _PyFunction_FastCallKeywords ()
#29 0x00007ffe414292fd in ?? ()
#30 0x00007ffe414473f1 in _PyEval_EvalFrameDefault ()
#31 0x00007ffe41403e35 in ?? ()
#32 0x00007ffe414292fd in ?? ()
#33 0x00007ffe414473f1 in _PyEval_EvalFrameDefault ()
#34 0x00007ffe41403e35 in ?? ()
#35 0x00007ffe414292fd in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#36 0x00007ffe41447351 in _PyEval_EvalFrameDefault ()
#37 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#38 0x00007ffe413f0d1e in PyEval_EvalCodeEx ()
#39 0x00007ffe413f0d3e in PyEval_EvalCode ()
#40 0x00007ffe414a902a in ?? ()
#41 0x00007ffe41416300 in _PyMethodDef_RawFastCallDict ()
#42 0x00007ffe41416456 in _PyCFunction_FastCallDict ()
#43 0x00007ffe4144771c in _PyEval_EvalFrameDefault ()
#44 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#45 0x00007ffe41403f94 in _PyFunction_FastCallKeywords ()
#46 0x00007ffe414292fd in ?? ()
#47 0x00007ffe41447351 in _PyEval_EvalFrameDefault ()
#48 0x00007ffe41403e35 in ?? ()
#49 0x00007ffe414292fd in ?? ()
#50 0x00007ffe4144736c in _PyEval_EvalFrameDefault ()
#51 0x00007ffe41403e35 in ?? ()
#52 0x00007ffe414292fd in ?? ()
#53 0x00007ffe414473f1 in _PyEval_EvalFrameDefault ()
#54 0x00007ffe41403e35 in ?? ()
#55 0x00007ffe414292fd in ?? ()
#56 0x00007ffe414473f1 in _PyEval_EvalFrameDefault ()
#57 0x00007ffe41403e35 in ?? ()
#58 0x00007ffe413f0dde in _PyFunction_FastCallDict ()
#59 0x00007ffe413f5a9b in ?? ()
#60 0x00007ffe41410acc in _PyObject_CallMethodIdObjArgs ()
#61 0x00007ffe413eea98 in PyImport_ImportModuleLevelObject ()
#62 0x00007ffe41445e6c in _PyEval_EvalFrameDefault ()
#63 0x00007ffe413f0c5b in _PyEval_EvalCodeWithName ()
#64 0x00007ffe413f0d1e in PyEval_EvalCodeEx ()
#65 0x00007ffe413f0d3e in PyEval_EvalCode ()
#66 0x00007ffe414a7895 in ?? ()
#67 0x00007ffe413d283f in PyRun_FileExFlags ()
#68 0x00007ffe413dabe1 in PyRun_SimpleFileExFlags ()
#69 0x00007ffe414bd64e in ?? ()
#70 0x00007ffe414bd810 in _Py_UnixMain ()
#71 0x00007ffe416078ae in libc_start_main_stage2 (main=0x7ffe415de058 <main>, argc=2, 
    argv=0x7ffe422b1010) at src/env/__libc_start_main.c:94
#72 0x00007ffe41607865 in __libc_start_main (main=0x7ffe415de058 <main>, argc=2, 
    argv=0x7ffe422b1010) at src/env/__libc_start_main.c:85
--Type <RET> for more, q to quit, c to continue without paging--
#73 0x00007ffe415de098 in _start_c ()
#74 0x00007ffe422b1008 in ?? ()
#75 0x00007ffe415de073 in _start ()
#76 0x0000000000000003 in ?? ()
#77 0x0000000000000002 in ?? ()
#78 0x00007ffe422b1225 in ?? ()
#79 0x00007ffe422b1236 in ?? ()
#80 0x0000000000000000 in ?? ()
```

**Comment by AevaOnline** [comment]
related to issue #188

**Comment by jxyang** [comment]
[Pseudo fork](https://github.com/deislabs/mystikos/blob/main/doc/design/fork.md) addresses the problem, but may introduced other problems.

Closing for now.
