### ISSUE TITLE
dotnet: ApplicationInsights crashes on creating a TelemetryClient

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#220]
The following C# application crashes on the constructor of TelemetryClient.

```c#
using System;
using Microsoft.ApplicationInsights;

namespace dotnet
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello C# World from Mystikos :-)");
            TelemetryClient client = new TelemetryClient();
            //client.TrackMetric("Alonglong", 42);
            //client.Flush();
        }
    }
}
```

**Comment by jxyang** [comment]
Nothing stands out as abnormal in the strace. The last few lines (before crash) are:

```
=== SYS_mprotect(addr=7f9367abf000 length=4096(1000) prot=3): tid=110
    SYS_mprotect(): return=0(0): tid=110
=== SYS_mprotect(addr=7f9367ad5000 length=4096(1000) prot=3): tid=110
    SYS_mprotect(): return=0(0): tid=110
=== SYS_mprotect(addr=7f9386212000 length=4096(1000) prot=3): tid=110
    SYS_mprotect(): return=0(0): tid=110
=== SYS_mprotect(addr=7f9386212000 length=4096(1000) prot=7): tid=110
    SYS_mprotect(): return=0(0): tid=110
=== SYS_mprotect(addr=7f9367ac0000 length=4096(1000) prot=3): tid=110
    SYS_mprotect(): return=0(0): tid=110
=== SYS_clock_gettime(clk_id=0 tp=0x7f9367e27e18): tid=110
    SYS_clock_gettime(): return=0(0): tid=110
myst_run_thread_ecall(): failed: retval=-1
2021-03-22T23:20:27+0000.567279Z [(H)ERROR] tid(0x7f94c17fa700) | :OE_ENCLAVE_ABORTING [/home/xuejun/mystikos/third_party/openenclave/openenclave/host/calls.c:_call_enclave_function_impl:56]
Makefile:14: recipe for target 'run' failed
make: *** [run] Aborted (core dumped)
```

**Comment by vtikoo** [comment]
Possibly its thread 110 exiting the enclave. Setting breakpoint on the thread exit code inside the enclave might give some usable backtrace?

**Comment by jxyang** [comment]
I managed to get the call stack from the managed exception:

```
Thread 1 "HelloWorld" received signal SIGILL, Illegal instruction.
Process terminated. Assertion failed.
   at System.Diagnostics.Tracing.EventWrittenEventArgs.get_Keywords()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsModule.DiagnosticsEventListener.OnEventWritten(EventWrittenEventArgs eventSourceEvent)
   at System.Diagnostics.Tracing.EventSource.WriteStringToAllListeners(String eventName, String msg)
   at System.Diagnostics.Tracing.EventSource.ReportOutOfBandMessage(String msg, Boolean flush)
   at System.Diagnostics.Tracing.EventSource.DoCommand(EventCommandEventArgs commandArgs)
   at System.Diagnostics.Tracing.EventSource.SendCommand(EventListener listener, EventProviderType eventProviderType, Int32 perEventSourceSessionId, Int32 etwSessionId, EventCommand command, Boolean enable, EventLevel level, EventKeywords matchAnyKeyword, IDictionary`2 commandArguments)
   at System.Diagnostics.Tracing.EventListener.EnableEvents(EventSource eventSource, EventLevel level, EventKeywords matchAnyKeyword, IDictionary`2 arguments)
   at System.Diagnostics.Tracing.EventListener.EnableEvents(EventSource eventSource, EventLevel level, EventKeywords matchAnyKeyword)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsModule.DiagnosticsEventListener..ctor(DiagnosticsListener listener, EventLevel logLevel)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsModule.DiagnosticsListener..ctor(IList`1 senders)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.Tracing.DiagnosticsTelemetryModule..ctor()
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules, String serializedConfiguration)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.TelemetryConfigurationFactory.Initialize(TelemetryConfiguration configuration, TelemetryModules modules)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.get_Active()
   at Microsoft.ApplicationInsights.TelemetryClient..ctor()
   at dotnet.Program.Main(String[] args)
```

Seems things have gone wrong in `DoCommand` and **ReportOutOfBandMessage_** is triggered to report an exception.

**Comment by jxyang** [comment]
This is caused by `dotnet publish` with option `/p:PublishTrimmed=true`. When trimming is on, `netstandard.dll`, a dependent library, is not placed in the self-contained folder.

Fixed it by removing  `/p:PublishTrimmed=true` from samples/solutions in #228
