### ISSUE TITLE
tests/dotnet-ubuntu fails sometimes in dlfree

### ISSUE THREAD

**Issue by vtikoo** [deislabs/mystikos#297]
dlfree from dlmalloc errors out ~1/100 times for the linux target.

The `free()` call is always from the context of verityblkdev cache eviction.
```
0x00007fffc6322262 in myst_crash () at /mnt/mystikos/include/myst/crash.h:11
11          *((volatile unsigned char*)0) = 0;
#0  0x00007fffc6322262 in myst_crash () at /mnt/mystikos/include/myst/crash.h:11
#1  0x00007fffc632239e in __myst_panic (file=0x7fffc637fbd0 "malloc.c", line=33, func=0x7fffc637fc30 <__FUNCTION__.3129> "_dlmalloc_abort", format=0x7fffc637fbc0 "dlmalloc failed") at panic.c:34
#2  0x00007fffc63542e2 in _dlmalloc_abort () at malloc.c:33
#3  0x00007fffc635b28d in dlfree (mem=0x7ffff67194b0) at ../third_party/dlmalloc/malloc.c:4776
#4  0x00007fffc635d11e in myst_free (ptr=0x7ffff67194b0) at malloc.c:136
#5  0x00007fffc635d18b in free (ptr=0x7ffff67194b0) at malloc.c:160
#6  0x00007fffc63772b7 in _cache_evict (dev=0x7ffff671d010) at verityblkdev.c:228
```

https://openenclave.visualstudio.com/ACC-Services/_build/results?buildId=6646&view=logs&j=ab477ad6-9781-5b54-82ca-a0141b26726e&t=a1e294d4-8895-5a45-41ff-022cede0621b&l=36998

**Comment by jxyang** [comment]
Haven't seen this in the pipeline for a while. Closing now.
