### ISSUE TITLE
Azure SDK tests: still waiting for child 102 to be killed, waiting_on_event: 0

### ISSUE THREAD

**Issue by Francis-Liu** [deislabs/mystikos#605]
https://openenclave.visualstudio.com/ACC-Services/_build/results?buildId=9179&view=logs&j=ab477ad6-9781-5b54-82ca-a0141b26726e&t=7ab7219c-d100-55c0-f286-28e73a950fa0

```

Key's updated expiry time is 07/15/2022 22:12:30 +00:00
Repeat #2...
Key is returned with name CloudRsaKey-c6901ad5-ce36-4e8f-9a94-641465d13238 and type RSA
Key's updated expiry time is 07/15/2022 22:13:52 +00:00
Repeat #3...
Key is returned with name CloudRsaKey-e60f2aeb-9235-4229-a326-608e3234421b and type RSA
Key's updated expiry time is 07/15/2022 22:14:21 +00:00
Success!
still waiting for child 113 to be killed, waiting_on_event: 1
make[2]: Leaving directory '/agent/_work/1/s/solutions/dotnet_azure_sdk/KeyVault_Keys'
make[2]: Entering directory '/agent/_work/1/s/solutions/dotnet_azure_sdk/KeyVault_Secrets'
Created /tmp/mystV7MmVS/lib/openenclave/mystenc.so.signed
Repeat #1...
Secret is returned with name BankAccountPassword-a50def98-096d-4626-acae-8464c1d09e04 and value f4G34fMh8v
Secret's updated expiry time is 07/15/2023 22:15:11 +00:00
Repeat #2...
Secret is returned with name BankAccountPassword-ef22ad65-eeb9-405a-a79f-020207e18614 and value f4G34fMh8v
Secret's updated expiry time is 07/15/2023 22:16:19 +00:00
Repeat #3...
Secret is returned with name BankAccountPassword-3857e8a3-033b-43d5-8974-999e1e5a49f0 and value f4G34fMh8v
Secret's updated expiry time is 07/15/2023 22:16:49 +00:00
Success!
still waiting for child 102 to be killed, waiting_on_event: 0
still waiting for child 110 to be killed, waiting_on_event: 0
still waiting for child 110 to be killed, waiting_on_event: 0
make[2]: Leaving directory '/agent/_work/1/s/solutions/dotnet_azure_sdk/KeyVault_Secrets'
make[2]: Entering directory '/agent/_work/1/s/solutions/dotnet_azure_sdk/KeyVault_Certificates'
Created /tmp/mystb10xQ6/lib/openenclave/mystenc.so.signed
Repeat #1...
Certificate was returned with name defaultCert-1655f56a-9d36-4e64-a271-3cbc42367ca6 which expires 07/15/2022 22:18:47 +00:00
Certificate enabled set to 'False'
Process terminated. Exception thrown from SocketAsyncEngine event loop: System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. EBADF
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Environment.FailFast(System.String, System.Exception)
   at System.Net.Sockets.SocketAsyncEngine.EventLoop()
   at System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__23_0(System.Object)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. EBADF
```

**Comment by bodzhang** [comment]
@Francis-Liu , can you check this test again? The related issue #611 was fixed.

**Comment by Francis-Liu** [comment]
> @Francis-Liu , can you check this test again? The related issue #611 was fixed.

@bodzhang I no longer see any error when I ran the tests today.
